/* Signing sketch content for sketch-home.html. ?s=<section>&lang=<en|de|ar>. Not product code. */
(function () {
  var q = new URLSearchParams(location.search);
  var s = q.get('s') || q.get('v') || 'routes';
  var lang = q.get('lang') || 'en';
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  var I = function (n, flip) { return '<span data-ico' + (flip ? ' data-flip' : '') + ' style="--m:url(../../../assets/icons/' + n + '.svg)" aria-hidden="true"></span>'; };
  var NOTE = { en: 'needs your text', de: 'needs your text', ar: 'needs your text' }[lang];
  var note = function () { return ' <span data-note>' + NOTE + '</span>'; };
  var P = '../../../assets/photography/';
  var CLS = 'https://vamostaxi.site/photos/classes/';
  var BIZ = CLS + '7f4a6dd2-245c-499d-9d11-a8d9d4fd34f9/458aece6-c409-4f3f-af58-93abb941854f.png';
  var T = {
    en: {
      hero: { card: 'From · To · When · Travellers · See prices', facts: ['Price fixed before you pay', 'Flight tracked', '60 minutes free waiting at the airport', 'Free cancellation until 24 hours before pickup'] },
      routes: { k: 'Popular routes', t: 'Routes our customers book most.', l: 'Tap a route and the booking card fills in the pickup and destination. You only add the date and travellers.', fixed: 'Fixed route', book: 'Book this route', more: 'Book', zrh: 'Zurich Airport', davos: 'Davos', stm: 'St. Moritz', rows: [['Zurich Airport', 'Zurich city'], ['Zurich Airport', 'Zermatt'], ['Zurich Airport', 'Lucerne'], ['Zurich Airport', 'Interlaken'], ['Geneva Airport', 'Lausanne'], ['Basel EuroAirport', 'Bern']], feat: 'Fixed price per class, set in advance' },
      meet: { k: 'At the airport', t: 'Where your driver waits.', l: 'Every airport pickup works the same way, whatever time you land.', steps: [['plane-landing', 'We track your flight', 'Your pickup time moves with the real arrival. Nothing to change if you land early or late.'], ['user', 'Name board in arrivals', 'Your driver waits after customs with your name on a board.'], ['clock', '60 minutes free waiting', 'Bags last off the belt or a long passport queue: the first hour is included.'], ['phone', 'Can’t see your driver?', 'Call or WhatsApp +41 79 626 70 82. We answer and guide you.']], sign: 'Your name', signSub: 'Vamos Taxi', points: 'Meeting point', ap: [['ZRH', 'Zurich'], ['GVA', 'Geneva'], ['BSL', 'Basel']] },
      services: { k: 'Services', t: 'What we drive.', l: 'One-way transfers, booked ahead, at a price fixed before you pay.', items: [['svc-airport.jpg', 'Airport transfers', 'To and from Zurich, Geneva and Basel airports, timed to your flight.'], ['svc-city.jpg', 'City to city', 'Door to door between Swiss cities, at the time you choose.'], [BIZ, 'Mountain and ski resorts', 'Davos, St. Moritz, Zermatt and the Alps. Tell us about skis when you book.'], ['svc-corporate.jpg', 'Business travel', 'Book for a guest or a colleague in their name.']], cta: 'Book' },
      reviews: { k: 'Reviews', t: 'What travellers say.', hidden: 'Fewer than 3 real reviews', hiddenP: 'The section and the hero rating do not show. Nothing is drawn from sample rows.', shown: 'From 3 real reviews', avg: 'Average of real published reviews', quote: 'Real quote, pasted from the platform', who: 'First name and initial', route: 'Zurich Airport → Zermatt', src: 'Read on Google' },
      trust: { k: 'Why book with us', t: 'A Swiss company, a price in writing.', facts: [['shield-check', 'Registered Swiss company', 'Vamos Taxi, Dietikon ZH. UID CHE-296.035.710.'], ['credit-card', 'Paid by card or TWINT', 'Payments go through Stripe. We never see your card number.'], ['receipt', 'Price fixed in writing', 'The fare is confirmed before you pay and does not change afterwards.'], ['calendar', 'Free cancellation', 'Cancel free of charge until 24 hours before pickup.'], ['car-front', 'Licensed and insured', 'Licence and insurance details.']] },
      business: { k: 'Business travel', t: 'Booking for guests or a team?', l: 'Book a ride in your guest’s name and send them the voucher. The receipt comes to you.', list: ['Book in a guest’s name', 'Receipt by email', 'One contact for every ride'], c1: 'Contact us', c2: 'WhatsApp' },
      faq: { k: 'Answers', t: 'Frequently asked questions', tabs: ['Booking and price', 'At the airport', 'Luggage and seats', 'Changes and cancellation'], qs: ['Where do I meet my driver?', 'What if my flight is late?', 'How long does the driver wait?', 'What if I can’t find my driver?', 'Can I book a pickup for someone else?'], a: 'After customs, in the arrivals hall. Your driver holds a board with your name.' },
      cta: { t: 'Your driver is waiting.', l: 'Fixed price, booked in under a minute.', b1: 'Book a transfer', b2: 'WhatsApp us' },
    },
    de: {
      hero: { card: 'Von · Nach · Wann · Reisende · Preise ansehen', facts: ['Preis fix vor der Zahlung', 'Flug wird verfolgt', '60 Minuten gratis Wartezeit am Flughafen', 'Gratis Stornierung bis 24 Stunden vor Abholung'] },
      routes: { k: 'Beliebte Strecken', t: 'Die Strecken, die am meisten gebucht werden.', l: 'Tippen Sie auf eine Strecke, und die Buchungskarte füllt Abholort und Ziel aus. Sie ergänzen nur Datum und Reisende.', fixed: 'Feste Strecke', book: 'Diese Strecke buchen', more: 'Buchen', zrh: 'Flughafen Zürich', davos: 'Davos', stm: 'St. Moritz', rows: [['Flughafen Zürich', 'Zürich Stadt'], ['Flughafen Zürich', 'Zermatt'], ['Flughafen Zürich', 'Luzern'], ['Flughafen Zürich', 'Interlaken'], ['Flughafen Genf', 'Lausanne'], ['EuroAirport Basel', 'Bern']], feat: 'Fester Preis je Klasse, im Voraus festgelegt' },
      meet: { k: 'Am Flughafen', t: 'Wo Ihr Fahrer wartet.', l: 'Jede Abholung am Flughafen läuft gleich, egal wann Sie landen.', steps: [['plane-landing', 'Wir verfolgen Ihren Flug', 'Die Abholzeit richtet sich nach der echten Ankunft. Bei früher oder später Landung müssen Sie nichts ändern.'], ['user', 'Namensschild in der Ankunftshalle', 'Ihr Fahrer wartet nach dem Zoll mit Ihrem Namen auf einem Schild.'], ['clock', '60 Minuten gratis Wartezeit', 'Gepäck kommt zuletzt oder die Passkontrolle dauert: Die erste Stunde ist inbegriffen.'], ['phone', 'Fahrer nicht gefunden?', 'Rufen Sie an oder schreiben Sie per WhatsApp an +41 79 626 70 82. Wir helfen Ihnen weiter.']], sign: 'Ihr Name', signSub: 'Vamos Taxi', points: 'Treffpunkt', ap: [['ZRH', 'Zürich'], ['GVA', 'Genf'], ['BSL', 'Basel']] },
      services: { k: 'Leistungen', t: 'Was wir fahren.', l: 'Einfache Fahrten, im Voraus gebucht, zu einem Preis, der vor der Zahlung feststeht.', items: [['svc-airport.jpg', 'Flughafentransfers', 'Zu und von den Flughäfen Zürich, Genf und Basel, abgestimmt auf Ihren Flug.'], ['svc-city.jpg', 'Stadt zu Stadt', 'Von Tür zu Tür zwischen Schweizer Städten, zur gewünschten Zeit.'], [BIZ, 'Berge und Skiorte', 'Davos, St. Moritz, Zermatt und die Alpen. Melden Sie Ski bei der Buchung an.'], ['svc-corporate.jpg', 'Geschäftsreisen', 'Buchen Sie für einen Gast oder eine Kollegin auf deren Namen.']], cta: 'Buchen' },
      reviews: { k: 'Bewertungen', t: 'Was Reisende sagen.', hidden: 'Weniger als 3 echte Bewertungen', hiddenP: 'Der Bereich und die Bewertung im Hero werden nicht angezeigt.', shown: 'Ab 3 echten Bewertungen', avg: 'Durchschnitt echter veröffentlichter Bewertungen', quote: 'Echtes Zitat, von der Plattform übernommen', who: 'Vorname und Initiale', route: 'Flughafen Zürich → Zermatt', src: 'Auf Google lesen' },
      trust: { k: 'Warum mit uns', t: 'Ein Schweizer Unternehmen, ein Preis schriftlich.', facts: [['shield-check', 'Eingetragenes Schweizer Unternehmen', 'Vamos Taxi, Dietikon ZH. UID CHE-296.035.710.'], ['credit-card', 'Bezahlt mit Karte oder TWINT', 'Zahlungen laufen über Stripe. Wir sehen Ihre Kartennummer nie.'], ['receipt', 'Preis schriftlich fix', 'Der Fahrpreis wird vor der Zahlung bestätigt und ändert sich danach nicht.'], ['calendar', 'Gratis Stornierung', 'Kostenlos stornieren bis 24 Stunden vor der Abholung.'], ['car-front', 'Bewilligt und versichert', 'Angaben zu Bewilligung und Versicherung.']] },
      business: { k: 'Geschäftsreisen', t: 'Buchen Sie für Gäste oder ein Team?', l: 'Buchen Sie eine Fahrt auf den Namen Ihres Gastes und senden Sie ihm den Voucher. Die Quittung geht an Sie.', list: ['Auf den Namen eines Gastes buchen', 'Quittung per E-Mail', 'Ein Kontakt für jede Fahrt'], c1: 'Kontakt', c2: 'WhatsApp' },
      faq: { k: 'Antworten', t: 'Häufige Fragen', tabs: ['Buchung und Preis', 'Am Flughafen', 'Gepäck und Sitze', 'Änderung und Stornierung'], qs: ['Wo treffe ich meinen Fahrer?', 'Was, wenn mein Flug Verspätung hat?', 'Wie lange wartet der Fahrer?', 'Was, wenn ich meinen Fahrer nicht finde?', 'Kann ich für jemand anderen buchen?'], a: 'Nach dem Zoll in der Ankunftshalle. Ihr Fahrer hält ein Schild mit Ihrem Namen.' },
      cta: { t: 'Ihr Fahrer wartet.', l: 'Fester Preis, in unter einer Minute gebucht.', b1: 'Transfer buchen', b2: 'WhatsApp' },
    },
    ar: {
      hero: { card: 'من · إلى · متى · المسافرون · عرض الأسعار', facts: ['السعر ثابت قبل الدفع', 'نتابع رحلتك الجوية', '60 دقيقة انتظار مجاني في المطار', 'إلغاء مجاني حتى 24 ساعة قبل الانطلاق'] },
      routes: { k: 'مسارات شائعة', t: 'المسارات الأكثر حجزًا.', l: 'اضغط على مسار فتُملأ نقطة الانطلاق والوجهة في بطاقة الحجز. تضيف أنت التاريخ والمسافرين فقط.', fixed: 'مسار ثابت', book: 'احجز هذا المسار', more: 'احجز', zrh: 'مطار زيورخ', davos: 'دافوس', stm: 'سانت موريتز', rows: [['مطار زيورخ', 'مدينة زيورخ'], ['مطار زيورخ', 'زيرمات'], ['مطار زيورخ', 'لوتسيرن'], ['مطار زيورخ', 'إنترلاكن'], ['مطار جنيف', 'لوزان'], ['مطار بازل', 'برن']], feat: 'سعر ثابت لكل فئة، محدد مسبقًا' },
      meet: { k: 'في المطار', t: 'أين ينتظرك السائق.', l: 'كل استقبال في المطار يتم بالطريقة نفسها، أيًا كان وقت هبوطك.', steps: [['plane-landing', 'نتابع رحلتك', 'يتغير وقت الاستقبال مع موعد الوصول الفعلي. لا داعي لتغيير شيء إذا هبطت مبكرًا أو متأخرًا.'], ['user', 'لافتة باسمك في صالة الوصول', 'ينتظرك السائق بعد الجمارك حاملًا لافتة باسمك.'], ['clock', '60 دقيقة انتظار مجاني', 'تأخرت الحقائب أو طال طابور الجوازات: الساعة الأولى مشمولة.'], ['phone', 'لا ترى السائق؟', 'اتصل أو راسلنا عبر واتساب على 82 70 626 79 41+. نجيبك ونرشدك.']], sign: 'اسمك', signSub: 'Vamos Taxi', points: 'نقطة اللقاء', ap: [['ZRH', 'زيورخ'], ['GVA', 'جنيف'], ['BSL', 'بازل']] },
      services: { k: 'الخدمات', t: 'ما نقدمه.', l: 'نقل باتجاه واحد، يُحجز مسبقًا، بسعر ثابت قبل الدفع.', items: [['svc-airport.jpg', 'النقل من وإلى المطار', 'من وإلى مطارات زيورخ وجنيف وبازل، بتوقيت رحلتك.'], ['svc-city.jpg', 'من مدينة إلى مدينة', 'من الباب إلى الباب بين المدن السويسرية، في الوقت الذي تختاره.'], [BIZ, 'الجبال ومنتجعات التزلج', 'دافوس وسانت موريتز وزيرمات وجبال الألب. أخبرنا بالزلاجات عند الحجز.'], ['svc-corporate.jpg', 'رحلات العمل', 'احجز لضيف أو زميل باسمه.']], cta: 'احجز' },
      reviews: { k: 'التقييمات', t: 'ماذا يقول المسافرون.', hidden: 'أقل من 3 تقييمات حقيقية', hiddenP: 'لا يظهر القسم ولا التقييم في أعلى الصفحة.', shown: 'من 3 تقييمات حقيقية', avg: 'متوسط التقييمات الحقيقية المنشورة', quote: 'اقتباس حقيقي منسوخ من المنصة', who: 'الاسم الأول والحرف الأول', route: 'مطار زيورخ ← زيرمات', src: 'اقرأ على Google' },
      trust: { k: 'لماذا تحجز معنا', t: 'شركة سويسرية، وسعر مكتوب.', facts: [['shield-check', 'شركة سويسرية مسجلة', 'Vamos Taxi، ديتيكون ZH. ‏UID CHE-296.035.710.'], ['credit-card', 'الدفع بالبطاقة أو TWINT', 'تتم المدفوعات عبر Stripe. لا نرى رقم بطاقتك أبدًا.'], ['receipt', 'سعر ثابت مكتوب', 'يُؤكَّد السعر قبل الدفع ولا يتغير بعد ذلك.'], ['calendar', 'إلغاء مجاني', 'ألغِ مجانًا حتى 24 ساعة قبل الانطلاق.'], ['car-front', 'مرخّصة ومؤمّنة', 'بيانات الترخيص والتأمين.']] },
      business: { k: 'رحلات العمل', t: 'تحجز لضيوف أو لفريق؟', l: 'احجز رحلة باسم ضيفك وأرسل له القسيمة. يصلك الإيصال.', list: ['احجز باسم ضيف', 'إيصال عبر البريد الإلكتروني', 'جهة اتصال واحدة لكل رحلة'], c1: 'تواصل معنا', c2: 'واتساب' },
      faq: { k: 'إجابات', t: 'الأسئلة الشائعة', tabs: ['الحجز والسعر', 'في المطار', 'الأمتعة والمقاعد', 'التعديل والإلغاء'], qs: ['أين ألتقي بالسائق؟', 'ماذا لو تأخرت رحلتي؟', 'كم ينتظر السائق؟', 'ماذا لو لم أجد السائق؟', 'هل يمكنني الحجز لشخص آخر؟'], a: 'بعد الجمارك، في صالة الوصول. يحمل السائق لافتة باسمك.' },
      cta: { t: 'سائقك في الانتظار.', l: 'سعر ثابت، يُحجز في أقل من دقيقة.', b1: 'احجز رحلة', b2: 'راسلنا عبر واتساب' },
    },
  }[lang];
  var head = function (o, dark) { return '<div data-head><p data-kicker>' + o.k + '</p><h2 data-title>' + o.t + '</h2>' + (o.l ? '<p data-lede>' + o.l + '</p>' : '') + '</div>'; };
  var sec = function (inner, dark) { return '<section data-sec' + (dark ? ' data-dark' : '') + '><div data-wrap>' + inner + '</div></section>'; };
  var html = '';
  if (s === 'hero') {
    var h = T.hero;
    html = '<section data-hero><div data-hero-in><div data-hero-card>' + h.card + '</div><div data-strip>' + h.facts.map(function (f) { return '<span>' + I('check') + f + '</span>'; }).join('') + '</div></div></section>';
  } else if (s === 'routes') {
    var r = T.routes;
    var feat = function (img, to) { return '<a data-route href="#book"><img src="' + img + '" alt=""><div data-route-body><span data-tag>' + r.fixed + '</span><div data-ends><span data-dot></span><span>' + r.zrh + '</span><span data-dot="end"></span><span>' + to + '</span></div><p data-p>' + r.feat + '</p><span data-link>' + r.book + I('arrow-right', 1) + '</span></div></a>'; };
    html = sec(head(r) + '<div data-grid style="--min:320px">' + feat(BIZ, r.davos) + feat(P + 'hero-oneway.jpg', r.stm) + '</div><div data-rows>' + r.rows.map(function (x) { return '<a data-row href="#book"><b>' + x[0] + ' → ' + x[1] + '</b><span>' + r.more + I('arrow-right', 1) + '</span></a>'; }).join('') + '</div>');
    if (lang === 'ar') html = html.replace(/ → /g, ' ← ');
  } else if (s === 'meet') {
    var m = T.meet;
    html = sec(head(m) + '<div data-meet><ol data-steps>' + m.steps.map(function (x) { return '<li><span data-tile>' + I(x[0]) + '</span><div style="display:flex;flex-direction:column;gap:6px"><h3 data-h3b>' + x[1] + '</h3><p data-p>' + x[2] + '</p></div></li>'; }).join('') + '</ol><div data-board><div data-sign>' + m.sign + '<small>' + m.signSub + '</small></div><div data-airports>' + m.ap.map(function (a) { return '<div data-ap><b class="vt-dir-keep">' + a[0] + '</b>' + a[1] + '<br>' + m.points + ':' + note() + '</div>'; }).join('') + '</div></div></div>', true);
  } else if (s === 'services') {
    var v = T.services;
    html = sec(head(v) + '<div data-grid style="--min:240px">' + v.items.map(function (x) { var src = x[0].indexOf('http') === 0 ? x[0] : P + x[0]; return '<a data-svc href="#book"><img src="' + src + '" alt=""><div data-svc-body><h3 data-h3>' + x[1] + '</h3><p data-p>' + x[2] + '</p><span data-link>' + v.cta + I('arrow-right', 1) + '</span></div></a>'; }).join('') + '</div>');
  } else if (s === 'reviews') {
    var w = T.reviews;
    var stars = '<span data-stars>' + [1, 2, 3, 4, 5].map(function () { return I('star'); }).join('') + '</span>';
    var card = '<article data-card><p data-quote>“' + w.quote + '”</p>' + stars + '<div data-who><b>' + w.who + '</b><span>' + w.route + '</span></div><span data-link>' + w.src + I('external-link') + '</span></article>';
    html = sec(head(w) + '<div data-split><div><p data-cap>' + w.hidden + '</p><div data-card style="border-style:dashed;min-block-size:160px;justify-content:center"><p data-p>' + w.hiddenP + '</p></div></div><div><p data-cap>' + w.shown + '</p><div data-rev-top><span data-score>4.9</span><div style="display:flex;flex-direction:column;gap:6px">' + stars + '<span data-p>' + w.avg + ' <span data-note>live number</span></span></div></div><div data-grid style="--min:200px">' + card + card + '</div></div></div>');
  } else if (s === 'trust') {
    var t = T.trust;
    html = sec(head(t) + '<div data-facts>' + t.facts.map(function (x, i) { return '<div data-fact><span data-tile>' + I(x[0]) + '</span><h3 data-h3>' + x[1] + '</h3><p data-p>' + x[2] + (i === 4 ? note() : '') + '</p></div>'; }).join('') + '</div>');
  } else if (s === 'business') {
    var b = T.business;
    html = sec('<div data-band><div data-band-copy><p data-kicker>' + b.k + '</p><h2 data-title>' + b.t + '</h2><p data-lede>' + b.l + '</p><ul data-band-list>' + b.list.map(function (x, i) { return '<li data-chip>' + I('check') + x + (i === 1 ? note() : '') + '</li>'; }).join('') + '</ul></div><div data-band-act><a data-btn href="/contact">' + b.c1 + I('arrow-right', 1) + '</a><a data-btn="ghost" href="#">' + I('message-circle') + b.c2 + '</a></div></div>');
  } else if (s === 'faq') {
    var f = T.faq;
    html = sec('<div data-faq><div data-head style="margin:0"><p data-kicker>' + f.k + '</p><h2 data-title>' + f.t + '</h2></div><div><div data-faq-tabs>' + f.tabs.map(function (x, i) { return '<span data-faq-tab aria-selected="' + (i === 1) + '">' + x + '</span>'; }).join('') + '</div>' + f.qs.map(function (x, i) { return '<div data-q' + (i === 0 ? ' data-open' : '') + '><span>' + x + '</span><span data-pm>' + I(i === 0 ? 'x' : 'plus') + '</span></div>' + (i === 0 ? '<div data-a><p data-p>' + f.a + '</p></div>' : ''); }).join('') + '</div></div>');
  } else if (s === 'cta') {
    var c = T.cta;
    html = sec('<div data-band><div data-band-copy><h2 data-cta-big>' + c.t + '</h2><p data-lede>' + c.l + '</p></div><div data-band-act><a data-btn="yellow" href="#book">' + c.b1 + I('arrow-right', 1) + '</a><a data-btn="ghost" style="min-block-size:54px" href="#">' + I('message-circle') + c.b2 + '</a></div></div>', true);
  }
  document.getElementById('root').innerHTML = html;
})();
