// Voucher cases through the real /checkout: percent voucher, and a fixed voucher bigger than the distance part.
// PAY, then read the saved lines and every page back. LANG_CODE, CODE (FLTEN | FLBIG), W (width).
import crypto from "node:crypto";
import fs from "node:fs";
import { launch, newContext, newPage, homeToCheckout, go, sql, rec, BASE, SHOTS } from "./lib.mjs";

const lang = process.env.LANG_CODE ?? "en";
const CODE = process.env.CODE ?? "FLTEN";
const W = Number(process.env.W ?? 1440);
const prefix = lang === "en" ? "" : "/" + lang;
const flat = (t) => t.replace(/\s+/g, " ").trim();
const COOKIE_BTN = /necessary only|nur notwendige|nécessaires uniquement|الضرورية فقط/i;
const browser = await launch();
const ctx = await newContext(browser, { lang, w: 1440, h: 900 });
const page = await newPage(ctx, []);
const intents = [];
page.on("response", async (r) => { if (new URL(r.url()).pathname.endsWith("/api/checkout/intent")) intents.push(r.status()); });
await homeToCheckout(page, lang);
await page.waitForTimeout(3500);
await page.locator("button", { hasText: COOKIE_BTN }).first().click({ timeout: 2000 }).catch(() => {});
await page.locator('[data-co-class="business"]').click();
await page.waitForTimeout(2000);
// The voucher: open the row, type the code, apply.
await page.locator("button", { hasText: /voucher|gutschein|bon|قسيمة|رمز/i }).filter({ hasNotText: /download|télécharger|herunter/i }).first().click();
await page.waitForTimeout(500);
const box = page.locator('input[type="text"]:visible').last();
await box.fill(CODE);
await box.press("Enter");
await page.waitForTimeout(3500);
const text = flat(await page.evaluate(() => [...document.querySelectorAll("[data-co-summary]")].find((e) => e.offsetParent)?.innerText ?? ""));
console.log("RAIL", text);
await page.screenshot({ path: `${SHOTS}/voucher-${CODE}-checkout-1440-${lang}.png` });
await page.locator("[data-co-rail]").first().screenshot({ path: `${SHOTS}/voucher-${CODE}-rail-1440-${lang}.png` });
rec(`voucher ${CODE} on the rail`, /Kloten/.test(text) && /8\.1|8,1/.test(text), text.slice(0, 400));
await page.locator('input[type="radio"]').first().check({ force: true });
const stamp = Date.now().toString(36);
const email = `flv-${CODE.toLowerCase()}-${lang}-${stamp}@example.com`;
await page.locator('input[autocomplete="given-name"]').fill("Anna");
await page.locator('input[autocomplete="family-name"]').fill("Keller");
await page.locator('input[autocomplete="email"]').fill(email);
await page.locator('input[autocomplete="tel"]').fill("790000000").catch(() => {});
await page.waitForTimeout(3000);
await page.locator('[data-co-pay-bar="rail"] [data-co-pay]').first().click({ timeout: 15000 });
for (let i = 0; i < 80 && intents.length === 0; i++) await page.waitForTimeout(250);
await page.waitForTimeout(1500);
rec(`PAY with ${CODE}`, intents[0] === 200, `intent ${intents[0]}`);
const cookies = await ctx.cookies();
await ctx.close();
const row = sql(`select b.reference||'|'||b.id||'|'||s.total_rappen||'|'||p.stripe_checkout_session_id from public.bookings b join public.price_snapshots s on s.id=b.price_snapshot_id join public.booking_payments p on p.snapshot_id=s.id where b.contact_email='${email}'`);
const [ref, bookingId, total, sessionId] = row.split("|");
const lines = JSON.parse(sql(`select s.lines::text from public.price_snapshots s join public.bookings b on b.price_snapshot_id=s.id where b.id='${bookingId}'`));
const sum = lines.reduce((a, l) => a + (l.amount_rappen ?? 0), 0);
const stripeAmount = (await (await fetch("http://127.0.0.1:4587/__sessions")).json()).find((s) => s.id === sessionId)?.amount_total;
rec(`saved lines with ${CODE}`, sum === Number(total) && Number(total) === stripeAmount && lines.every((l) => l.amount_rappen == null || l.amount_rappen >= 0),
  `total=${total} stripe=${stripeAmount} sum=${sum} ${JSON.stringify(lines.map((l) => [l.code, l.amount_rappen, l.params?.list_rappen ?? l.params?.discount_rappen ?? null]))}`);
fs.writeFileSync(`/private/tmp/vamos-fl/state-v-${CODE}-${lang}.json`, JSON.stringify({ ref, bookingId, sessionId, total, email, cookies, lines }));

// Pay link page, then settle, then confirmation and manage booking.
const raw = crypto.randomBytes(32);
const token = raw.toString("base64url");
sql(`select public.checkout_set_pay_link('${bookingId}'::uuid, 'individual', '', '', '', 'payer@example.com', decode('${crypto.createHash("sha256").update(raw).digest("hex")}','hex'), now() + interval '24 hours')`);
const c2 = await newContext(browser, { lang, w: W, h: W >= 1000 ? 900 : 844 });
const p2 = await newPage(c2, []);
await go(p2, `${BASE}${prefix}/checkout/pay/${token}`);
await p2.waitForTimeout(4500);
const pt = flat(await p2.locator("[data-pay-link-price]").first().innerText().catch(() => ""));
await p2.screenshot({ path: `${SHOTS}/voucher-${CODE}-paylink-${W}-${lang}.png` });
console.log("PAYLINK", pt);
rec(`pay link with ${CODE}`, /Kloten/.test(pt) && !/(-|−)\s*CHF 0\.00/.test(pt), pt.slice(0, 400));
await c2.close();
sql(`select count(*) from public.checkout_payment_settle('evt_flv_${CODE}_${lang}_${Date.now()}', '${sessionId}', 'pi_flv_${CODE}', 'succeeded', null, null, null, null, null, null)`);
const c3 = await newContext(browser, { lang, w: W, h: W >= 1000 ? 900 : 844 });
await c3.addCookies(cookies.map((c) => ({ ...c, url: undefined, domain: "localhost", path: "/" })));
const p3 = await newPage(c3, []);
await go(p3, `${BASE}${prefix}/confirmation/${ref}`);
await p3.waitForTimeout(4500);
const ct = flat(await p3.locator("[data-confirmation-voucher]").first().innerText().catch(() => ""));
await p3.screenshot({ path: `${SHOTS}/voucher-${CODE}-confirmation-${W}-${lang}.png`, fullPage: true });
console.log("CONFIRMATION", ct);
rec(`confirmation with ${CODE}`, /Kloten/.test(ct), ct.slice(0, 420));
await go(p3, `${BASE}/manage-booking`);
await p3.waitForTimeout(5000);
const mt = flat(await p3.evaluate(() => document.body.innerText));
await p3.screenshot({ path: `${SHOTS}/voucher-${CODE}-manage-${W}-${lang}.png`, fullPage: true });
const mi = mt.indexOf(mt.match(/YOU PAID|BEZAHLT HABEN|AVEZ PAYÉ|دفعته/)?.[0] ?? "zzz");
console.log("MANAGE", mt.slice(mi, mi + 300));
rec(`manage with ${CODE}`, /Kloten/.test(mt), mt.slice(mi, mi + 300));
await c3.close();
await browser.close();
