#!/usr/bin/env node
// Compares two mirror-check --json outputs (before, after) and prints a Markdown table:
// one row per spot / icon place / icon, with the x-scale product in ar and en at each width, before -> after.
// usage: node mirror-compare.mjs <before.json> <after.json>
import { readFileSync } from "node:fs";

const [beforeFile, afterFile] = process.argv.slice(2);
const load = (f) => JSON.parse(readFileSync(f, "utf8"));
const before = load(beforeFile);
const after = load(afterFile);

// `.scpN` classes are generated by the DC runtime per render; they are not part of the place.
const keyOf = (r) => `${r.spot}|${r.path.replace(/\.scp\d+/g, "")}|${r.icon}`;
const cellOf = (r) => `${r.lang} ${r.width}`;
const sign = (n) => (n === undefined ? "–" : n > 0 ? "+1" : "−1");

/** key -> cell -> {products:Set, ok:boolean} */
function index(rows) {
  const m = new Map();
  for (const r of rows) {
    if (!r.icon) continue;
    const k = keyOf(r);
    if (!m.has(k)) m.set(k, new Map());
    const c = m.get(k);
    const cell = cellOf(r);
    const prev = c.get(cell) || { products: new Set(), ok: true };
    prev.products.add(r.product);
    prev.ok = prev.ok && r.ok;
    c.set(cell, prev);
  }
  return m;
}
const b = index(before);
const a = index(after);
const keys = [...new Set([...b.keys(), ...a.keys()])];
const cells = ["ar 1440", "ar 390", "en 1440", "en 390"];
const show = (entry) => {
  if (!entry) return "–";
  const s = [...entry.products].map(sign).join("/");
  return entry.ok ? s : `**${s}** FAIL`;
};

console.log(`| spot | icon place | icon | ${cells.map((c) => `${c} before → after`).join(" | ")} |`);
console.log(`|---|---|---|${cells.map(() => "---").join("|")}|`);
for (const k of keys) {
  const [spot, path, icon] = k.split("|");
  const row = cells.map((c) => `${show(b.get(k)?.get(c))} → ${show(a.get(k)?.get(c))}`);
  console.log(`| ${spot} | \`${path}\` | ${icon} | ${row.join(" | ")} |`);
}

const errs = (rows, label) =>
  rows.filter((r) => r.error).map((r) => `- ${label}: ${r.spot} ${r.lang} ${r.width} — ${r.error}`);
const notes = [...errs(before, "before"), ...errs(after, "after")];
if (notes.length) {
  console.log("\nSpots that did not run:\n");
  console.log(notes.join("\n"));
}
const count = (rows) => ({
  icons: rows.filter((r) => r.icon).length,
  fail: rows.filter((r) => r.icon && !r.ok).length,
});
const cb = count(before);
const ca = count(after);
console.log(`\nbefore: ${cb.icons} icon readings, ${cb.fail} not as expected · after: ${ca.icons} icon readings, ${ca.fail} not as expected`);
