// apps/web/tests/e2e-specs.ts
//
// 26.0 D-01: the one list of specs that need `next dev` and/or a local Supabase stack. The macOS
// CI job (offline darwin screenshots, no Docker) ignores exactly this list; the Linux e2e job runs
// exactly this list (VAMOS_E2E=1) with screenshot assertions skipped. Locally, with neither CI nor
// VAMOS_E2E set, every spec runs. playwright.config.ts is the only consumer.
//
// Add a spec here when it boots Next, reads the database, or skips itself when the stack is down.
export const E2E_SPECS: string[] = [
  "**/content-loader-parity.spec.ts",
  "**/about.spec.ts",
  "**/account-session-guard.spec.ts",
  "**/auth-confirm-email.spec.ts",
  "**/auth-flows.spec.ts",
  "**/auth-forms.spec.ts",
  "**/auth-session.spec.ts",
  "**/auth-signout.spec.ts",
  "**/checkout-page.spec.ts",
  "**/checkout-pay-19.spec.ts",
  "**/checkout-hosted.spec.ts",
  "**/checkout-languages-22.spec.ts",
  "**/checkout-server-db.spec.ts",
  "**/intent-supersede-db.spec.ts",
  "**/extras-charged-recorded-db.spec.ts",
  "**/account-bookings-26-3.spec.ts",
  "**/account-i18n-coverage-26-3.spec.ts",
  "**/locale-follow-26-3.spec.ts",
  "**/checkout-sections.spec.ts",
  "**/checkout-account.spec.ts",
  "**/checkout-other-device-265.spec.ts",
  "**/pay-link-page.spec.ts",
  "**/confirmation.spec.ts",
  "**/confirmation-poll.spec.ts",
  "**/contact.spec.ts",
  "**/contact-form.spec.ts",
  "**/contact-lifecycle.spec.ts",
  "**/content-string-edit.spec.ts",
  "**/currency.spec.ts",
  "**/dev-exclusion.spec.ts",
  "**/email-hook.spec.ts",
  "**/error-pages.spec.ts",
  "**/faq.spec.ts",
  "**/feedback-behaviour.spec.ts",
  "**/home.spec.ts",
  "**/home-content.spec.ts",
  "**/home-hero.spec.ts",
  "**/home-how-it-works.spec.ts",
  "**/home-reviews.spec.ts",
  "**/home-services.spec.ts",
  "**/home-widget.spec.ts",
  "**/home-why-vamos.spec.ts",
  "**/lang-switch.spec.ts",
  "**/legal-cancellation-imprint.spec.ts",
  "**/legal-notice.spec.ts",
  "**/legal-privacy-cookies.spec.ts",
  "**/legal-terms.spec.ts",
  "**/public-routes.spec.ts",
  "**/quote-api.spec.ts",
  "**/ssr-locale.spec.ts",
  "**/ops-claims-bridge.spec.ts",
];
